# Assembly generated by ecc (Evil C Compiler)

.data
	str_0: .asciiz "\n"

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall 
fib:
        addi    $sp, $sp, -24
        sw      $ra, 20($sp)

        move    $t0, $a0
        li      $t1, 2
        bge     $t0, $t1, if_0

        move    $v0, $a0
        lw      $ra, 20($sp)
        addi    $sp, $sp, 24
        jr      $ra

if_0:
        li      $t0, 0
        sw      $t0, 16($sp)

        li      $t0, 1
        sw      $t0, 12($sp)

        li      $t0, 2
        sw      $t0, 8($sp)

        j       for_0_end
for_0_body:
        lw      $t0, 16($sp)
        lw      $t1, 12($sp)
        add     $t2, $t0, $t1
        sw      $t2, 4($sp)

        lw      $t0, 12($sp)
        sw      $t0, 16($sp)

        lw      $t0, 4($sp)
        sw      $t0, 12($sp)

        lw      $t0, 8($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 8($sp)

for_0_end:
        lw      $t0, 8($sp)
        move    $t1, $a0
        ble     $t0, $t1, for_0_body

        lw      $v0, 12($sp)
        lw      $ra, 20($sp)
        addi    $sp, $sp, 24
        jr      $ra

main:
        addi    $sp, $sp, -12
        sw      $ra, 8($sp)

        li      $t0, 0
        sw      $t0, 4($sp)

        j       for_1_end
for_1_body:
        lw      $a0, 4($sp)
        jal     fib
        sw      $v0, 0($sp)

        lw      $a0, 0($sp)
        li      $v0, 1
        syscall 

        la      $a0, str_0
        li      $v0, 4
        syscall 

        lw      $t1, 4($sp)
        li      $t2, 1
        add     $t1, $t1, $t2
        sw      $t1, 4($sp)

for_1_end:
        lw      $t1, 4($sp)
        li      $t2, 10
        blt     $t1, $t2, for_1_body

        lw      $ra, 8($sp)
        addi    $sp, $sp, 12
        jr      $ra