# Assembly generated by ecc (Evil C Compiler)

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall 
main:
        addi    $sp, $sp, -12
        sw      $ra, 8($sp)

        li      $t0, 10
        sw      $t0, 4($sp)

while_1_body:
        li      $t0, 0
        sw      $t0, 0($sp)

while_0_body:
        lw      $t0, 0($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 0($sp)

while_0_end:
        lw      $t0, 0($sp)
        lw      $t1, 4($sp)
        blt     $t0, $t1, while_0_body

        lw      $t0, 4($sp)
        li      $t1, 1
        sub     $t0, $t0, $t1
        sw      $t0, 4($sp)

while_1_end:
        lw      $t0, 4($sp)
        li      $t1, 0
        bgt     $t0, $t1, while_1_body

        lw      $ra, 8($sp)
        addi    $sp, $sp, 12

        jr      $ra