# Assembly generated by ecc (Evil C Compiler)

.data
	str_0: .asciiz "Input a number: "
	str_1: .asciiz "\n"
	str_2: .asciiz "!: "

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall 
mult:
        addi    $sp, $sp, -20
        sw      $ra, 16($sp)

        sw      $a0, 12($sp)
        sw      $a1, 8($sp)
        li      $t0, 0
        sw      $t0, 4($sp)

        li      $t0, 0
        sw      $t0, 0($sp)

        j       for_0_end

for_0_body:
        lw      $t0, 4($sp)
        lw      $t1, 12($sp)
        add     $t0, $t0, $t1
        sw      $t0, 4($sp)

        lw      $t0, 0($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 0($sp)

for_0_end:
        lw      $t0, 0($sp)
        lw      $t1, 8($sp)
        blt     $t0, $t1, for_0_body

        lw      $v0, 4($sp)
        lw      $ra, 16($sp)
        addi    $sp, $sp, 20
        jr      $ra

fac:
        addi    $sp, $sp, -16
        sw      $ra, 12($sp)

        sw      $a0, 8($sp)
        li      $t0, 1
        sw      $t0, 4($sp)

        li      $t0, 1
        sw      $t0, 0($sp)

        j       for_1_end

for_1_body:
        lw      $a0, 4($sp)
        lw      $a1, 0($sp)
        jal     mult
        sw      $v0, 4($sp)

        lw      $t0, 0($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 0($sp)

for_1_end:
        lw      $t0, 0($sp)
        lw      $t1, 8($sp)
        ble     $t0, $t1, for_1_body

        lw      $v0, 4($sp)
        lw      $ra, 12($sp)
        addi    $sp, $sp, 16
        jr      $ra

main:
        addi    $sp, $sp, -12
        sw      $ra, 8($sp)

        la      $a0, str_0
        li      $v0, 4
        syscall 

        li      $v0, 5
        syscall 
        sw      $v0, 4($sp)

        lw      $a0, 4($sp)
        jal     fac
        sw      $v0, 0($sp)

        la      $a0, str_1
        li      $v0, 4
        syscall 

        lw      $a0, 4($sp)
        li      $v0, 1
        syscall 

        la      $a0, str_2
        li      $v0, 4
        syscall 

        lw      $a0, 0($sp)
        li      $v0, 1
        syscall 

        lw      $ra, 8($sp)
        addi    $sp, $sp, 12
        jr      $ra

