# Assembly generated by ecc (Evil C Compiler)

.data
	str_0: .asciiz "Too low!\n"
	str_1: .asciiz "Too high!\n"
	str_2: .asciiz "Guess a number between 1 and "
	str_3: .asciiz ": "
	str_4: .asciiz "\n"
	str_5: .asciiz "You found the number!: "
	str_6: .asciiz "\nIt took you "
	str_7: .asciiz " guesses!\n"
	str_8: .asciiz "\n\nPlay again? (1 for yes, 0 for no): "

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall

printHint:
        addi    $sp, $sp, -12
        sw      $ra, 8($sp)

        sw      $a0, 4($sp)
        sw      $a1, 0($sp)
        lw      $t0, 4($sp)
        lw      $t1, 0($sp)
        bge     $t0, $t1, if_0

        la      $a0, str_0
        li      $v0, 4
        syscall

        li      $t0, 1
        move    $v0, $t0
        lw      $ra, 8($sp)
        addi    $sp, $sp, 12
        jr      $ra

if_0:
        lw      $t1, 4($sp)
        lw      $t2, 0($sp)
        ble     $t1, $t2, if_1

        la      $a0, str_1
        li      $v0, 4
        syscall

        li      $t1, 1
        move    $v0, $t1
        lw      $ra, 8($sp)
        addi    $sp, $sp, 12
        jr      $ra

if_1:
        li      $t2, 0
        move    $v0, $t2
        lw      $ra, 8($sp)
        addi    $sp, $sp, 12
        jr      $ra

main:
        addi    $sp, $sp, -28
        sw      $ra, 24($sp)

        li      $t0, 1
        sw      $t0, 20($sp)

        li      $t0, 10000
        sw      $t0, 16($sp)

        j       while_1_end

while_1_body:
        li      $t0, 0
        sw      $t0, 12($sp)

        li      $t0, 1
        sw      $t0, 8($sp)

        li      $a0, 40
        lw      $a1, 16($sp)
        li      $v0, 42
        syscall
        sw      $a0, 4($sp)

        lw      $t1, 4($sp)
        li      $t2, 1
        add     $t1, $t1, $t2
        sw      $t1, 4($sp)

        li      $t1, 0
        sw      $t1, 0($sp)

        j       while_0_end

while_0_body:
        la      $a0, str_2
        li      $v0, 4
        syscall

        lw      $a0, 16($sp)
        li      $v0, 1
        syscall

        la      $a0, str_3
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 0($sp)


        lw      $a0, 0($sp)
        lw      $a1, 4($sp)
        jal     printHint
        sw      $v0, 8($sp)


        la      $a0, str_4
        li      $v0, 4
        syscall

        lw      $t1, 12($sp)
        li      $t2, 1
        add     $t1, $t1, $t2
        sw      $t1, 12($sp)

while_0_end:
        lw      $t1, 8($sp)
        li      $t2, 0
        bne     $t1, $t2, while_0_body

        la      $a0, str_5
        li      $v0, 4
        syscall

        lw      $a0, 4($sp)
        li      $v0, 1
        syscall

        la      $a0, str_6
        li      $v0, 4
        syscall

        lw      $a0, 12($sp)
        li      $v0, 1
        syscall

        la      $a0, str_7
        li      $v0, 4
        syscall

        la      $a0, str_8
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 20($sp)


while_1_end:
        lw      $t1, 20($sp)
        li      $t2, 0
        bgt     $t1, $t2, while_1_body

        lw      $ra, 24($sp)
        addi    $sp, $sp, 28
        jr      $ra

