# Assembly generated by ecc (Evil C Compiler)

.data
	str_0: .asciiz "*"
	str_1: .asciiz " "
	str_2: .asciiz "\n"
	str_3: .asciiz "Enter stars height: "
	str_4: .asciiz "Backwards? (1 for yes, 0 for no): "

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall 
stars:
        addi    $sp, $sp, -28
        sw      $ra, 24($sp)

        sw      $a0, 20($sp)
        sw      $a1, 16($sp)
        li      $t0, 0
        sw      $t0, 12($sp)

        j       for_3_end

for_3_body:
        lw      $t0, 16($sp)
        beq     $t0, $zero, if_0

        li      $t0, 0
        sw      $t0, 8($sp)

        j       for_0_end

for_0_body:
        la      $a0, str_0
        li      $v0, 4
        syscall 

        lw      $t0, 8($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 8($sp)

for_0_end:
        lw      $t0, 8($sp)
        lw      $t1, 12($sp)
        blt     $t0, $t1, for_0_body

if_0:
        lw      $t0, 16($sp)
        bne     $t0, $zero, if_1

        lw      $t0, 20($sp)
        lw      $t1, 12($sp)
        sub     $t2, $t0, $t1
        sw      $t2, 4($sp)

        j       for_1_end

for_1_body:
        la      $a0, str_1
        li      $v0, 4
        syscall 

        lw      $t0, 4($sp)
        li      $t1, 1
        sub     $t0, $t0, $t1
        sw      $t0, 4($sp)

for_1_end:
        lw      $t0, 4($sp)
        li      $t1, 0
        bge     $t0, $t1, for_1_body

        li      $t0, 0
        sw      $t0, 4($sp)

        j       for_2_end

for_2_body:
        la      $a0, str_0
        li      $v0, 4
        syscall 

        lw      $t0, 4($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 4($sp)

for_2_end:
        lw      $t0, 4($sp)
        lw      $t1, 12($sp)
        blt     $t0, $t1, for_2_body

if_1:
        la      $a0, str_2
        li      $v0, 4
        syscall 

        lw      $t0, 12($sp)
        li      $t1, 1
        add     $t0, $t0, $t1
        sw      $t0, 12($sp)

for_3_end:
        lw      $t0, 12($sp)
        lw      $t1, 20($sp)
        ble     $t0, $t1, for_3_body

        lw      $ra, 24($sp)
        addi    $sp, $sp, 28
        jr      $ra

main:
        addi    $sp, $sp, -16
        sw      $ra, 12($sp)

        la      $a0, str_3
        li      $v0, 4
        syscall 

        li      $v0, 5
        syscall 
        sw      $v0, 8($sp)

        la      $a0, str_4
        li      $v0, 4
        syscall 

        li      $v0, 5
        syscall 
        sw      $v0, 4($sp)

        li      $t2, 0
        sw      $t2, 0($sp)

        lw      $t2, 4($sp)
        li      $t3, 1
        beq     $t2, $t3, if_2

        li      $t2, 1
        sw      $t2, 0($sp)

if_2:
        la      $a0, str_2
        li      $v0, 4
        syscall 

        lw      $a0, 8($sp)
        lw      $a1, 0($sp)
        jal     stars

        lw      $ra, 12($sp)
        addi    $sp, $sp, 16
        jr      $ra

