# Assembly generated by ecc (Evil C Compiler)

.data
	str_0: .asciiz "Is the number "
	str_1: .asciiz "? (0 for yes, 1 for lower, 2 for higher): "
	str_2: .asciiz "Enter range min: "
	str_3: .asciiz "Enter range max: "
	str_4: .asciiz "\n"
	str_5: .asciiz "Think of a number between "
	str_6: .asciiz " and "
	str_7: .asciiz "Hooray, I guessed the number!\n"
	str_8: .asciiz "It took me "
	str_9: .asciiz " guesses\n\nWould you like to play again? (1 for yes, 0 for no): "

.text
.globl _start

_start:
        jal     main
        li      $v0, 10
        syscall

abs:
        subi    $sp, $sp, 8
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)

        lw      $t0, 4($sp)
        li      $t1, 0
        bge     $t0, $t1, if_0

        lw      $t0, 4($sp)
        li      $t1, -1
        mulo    $t0, $t0, $t1
        sw      $t0, 4($sp)

if_0:
        lw      $v0, 4($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 8
        jr      $ra

getGuess:
        subi    $sp, $sp, 16
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)
        sw      $a1, 8($sp)

        lw      $t0, 4($sp)
        lw      $t1, 8($sp)
        add     $t2, $t0, $t1
        sw      $t2, 12($sp)

        lw      $t0, 12($sp)
        li      $t1, 0
        bge     $t0, $t1, if_1

        lw      $a0, 12($sp)
        jal     abs
        sw      $v0, 12($sp)


        lw      $t0, 12($sp)
        srl     $t0, $t0, 1
        sw      $t0, 12($sp)

        lw      $t1, 12($sp)
        li      $t2, -1
        mulo    $t1, $t1, $t2
        sw      $t1, 12($sp)

        lw      $v0, 12($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 16
        jr      $ra

if_1:
        lw      $t1, 12($sp)
        srl     $t1, $t1, 1
        sw      $t1, 12($sp)

        lw      $v0, 12($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 16
        jr      $ra

askQuestion:
        subi    $sp, $sp, 12
        sw      $ra, 0($sp)
        sw      $a0, 4($sp)

        la      $a0, str_0
        li      $v0, 4
        syscall

        lw      $a0, 4($sp)
        li      $v0, 1
        syscall

        la      $a0, str_1
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 8($sp)

        lw      $v0, 8($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 12
        jr      $ra

promptMin:
        subi    $sp, $sp, 8
        sw      $ra, 0($sp)

        la      $a0, str_2
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 4($sp)

        lw      $v0, 4($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 8
        jr      $ra

promptMax:
        subi    $sp, $sp, 8
        sw      $ra, 0($sp)

        la      $a0, str_3
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 4($sp)

        lw      $v0, 4($sp)
        lw      $ra, 0($sp)
        addi    $sp, $sp, 8
        jr      $ra

main:
        subi    $sp, $sp, 40
        sw      $ra, 0($sp)

        jal     promptMin
        sw      $v0, 4($sp)

        jal     promptMax
        sw      $v0, 8($sp)

        li      $t2, 1
        sw      $t2, 12($sp)

        la      $a0, str_4
        li      $v0, 4
        syscall

        j       while_1_end

while_1_body:
        lw      $t2, 4($sp)
        sw      $t2, 16($sp)

        lw      $t2, 8($sp)
        sw      $t2, 20($sp)

        li      $t2, 0
        sw      $t2, 24($sp)

        la      $a0, str_5
        li      $v0, 4
        syscall

        lw      $a0, 16($sp)
        li      $v0, 1
        syscall

        la      $a0, str_6
        li      $v0, 4
        syscall

        lw      $a0, 20($sp)
        li      $v0, 1
        syscall

        la      $a0, str_4
        li      $v0, 4
        syscall

        li      $t2, 1
        sw      $t2, 28($sp)

        lw      $a0, 16($sp)
        lw      $a1, 20($sp)
        jal     getGuess
        sw      $v0, 32($sp)

        j       while_0_end

while_0_body:
        lw      $a0, 32($sp)
        jal     askQuestion
        sw      $v0, 28($sp)


        lw      $t3, 28($sp)
        li      $t4, 1
        bne     $t3, $t4, if_2

        lw      $t3, 32($sp)
        li      $t4, 1
        sub     $t3, $t3, $t4
        sw      $t3, 20($sp)

if_2:
        lw      $t3, 28($sp)
        li      $t4, 2
        bne     $t3, $t4, if_3

        lw      $t3, 32($sp)
        li      $t4, 1
        add     $t3, $t3, $t4
        sw      $t3, 16($sp)

if_3:
        lw      $a0, 16($sp)
        lw      $a1, 20($sp)
        jal     getGuess
        sw      $v0, 32($sp)


        lw      $t3, 24($sp)
        li      $t4, 1
        add     $t3, $t3, $t4
        sw      $t3, 24($sp)

while_0_end:
        lw      $t3, 28($sp)
        li      $t4, 0
        bne     $t3, $t4, while_0_body

        la      $a0, str_7
        li      $v0, 4
        syscall

        la      $a0, str_8
        li      $v0, 4
        syscall

        lw      $a0, 24($sp)
        li      $v0, 1
        syscall

        la      $a0, str_9
        li      $v0, 4
        syscall

        li      $v0, 5
        syscall
        sw      $v0, 36($sp)

        li      $t4, 1
        sw      $t4, 12($sp)

        lw      $t4, 36($sp)
        li      $t5, 0
        bne     $t4, $t5, if_4

        li      $t4, 0
        sw      $t4, 12($sp)

if_4:
        la      $a0, str_4
        li      $v0, 4
        syscall

while_1_end:
        lw      $t4, 12($sp)
        bne     $t4, $zero, while_1_body

        lw      $ra, 0($sp)
        addi    $sp, $sp, 40
        jr      $ra

